### ISSUE TITLE
The driver cannot compile with Mbed OS 5.11.2 and above.

### ISSUE THREAD

**Issue by screamerbg** [OpenNuvoton/NuMaker-mbed-SD-driver#1]
Due to the following change https://github.com/ARMmbed/mbed-os/pull/9135, I get the following compiler error while compiling Pelion example with Mbed OS 5.11.2:

```
[DEBUG] Output: ".\drivers\storage\MySystemStorage.cpp", line 110: Error:  #322: object of abstract class type "NuSDBlockDevice" is not allowed:
[DEBUG] Output:             pure virtual function "mbed::BlockDevice::get_type"  has no overrider
```

CC @cyliangtw @samchuarm

**Comment by cyliangtw** [comment]
@screamerbg , about this new virtual function of blockdevice classes, we will implement to fulfill OS 5.12, we will also need to modify the combination of` mbed-os.lib` and `COMPONENT_NUSD.lib` in pelion-example-common.

CC @samchuarm

**Comment by dannybenor** [comment]
Please add this simple function that returns the name of the BD. It is much simpler than revert the changes in 5.11.2.

**Comment by cyliangtw** [comment]
@dannybenor , it's OK to finish the test by tomorrow.
Next time, it's better to provide one default implementation instead of pure virtual function for backward compatible, for ex `return "unknown"`.
